Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  # Define control_plane VM
  config.vm.define "control_plane" do |control_plane|
    control_plane.vm.hostname = "control-plane"
    control_plane.vm.network "private_network", ip: "192.168.56.11"

    # Shared folder using 9p for libvirt
    control_plane.vm.synced_folder "./shared_folder_control_plane", "/home/vagrant/shared_folder",
      type: "9p", accessmode: "mapped", id: "control_share"

    control_plane.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end
  end

  # Define worker VM
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: "192.168.56.12"

    # Shared folder using 9p for libvirt
    worker.vm.synced_folder "./shared_folder_worker", "/home/vagrant/shared_folder",
      type: "9p", accessmode: "mapped", id: "worker_share"

    worker.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end
  end
end
