- name: Copy installer to control plane
  copy:
    src: "{{ playbook_dir }}/../files/k8s_installer.run"
    dest: /root/k8s_installer.run
    mode: '0755'

- name: Run installer with control_plane role as root
  shell: sudo -i /root/k8s_installer.run -- -r master -m {{ ansible_host }}
  args:
    executable: /bin/bash

- name: Fetch join command back to Ansible host
  fetch:
    src: /root/join_command.sh
    dest: /tmp/join_command.sh
    flat: yes
