- name: Copy installer to control plane
  copy:
    src: "../../../../k8s_installer.run"
    dest: /tmp/k8s_installer.run
    mode: '0755'

- name: Run installer with control_plane role as root
  shell: sudo -i /tmp/k8s_installer.run -- -r control_plane -m {{ ansible_host }}
  args:
    executable: /bin/bash

- name: Fetch join command back to Ansible host
  fetch:
    src: /tmp/join_command.sh
    dest: /tmp/join_command.sh
    flat: yes
