pipeline {
    agent {
        label 'd-workers'
    }

    environment {
        PROJECT_DIR = 'Offline_Vanilla_k8s_Installer'
        INSTALLER_NAME = 'instaler.run'
        INSTALL_SCRIPT = './automation-scripts/install.sh'
        COMMENT = 'k8s_install'
    }

    stages {
        stage('Pre Build') {
            steps {
                sh '''
                    apt-get update
                    apt-get install -y makeself shellcheck
                '''
            }
        }

    stage('Lint') {
        steps {
            script {
                def result = sh(script:
                """
                    if ! shellcheck ${INSTALL_SCRIPT}; then
                        echo "There was a problem with script syntax, stopping the build..."
                        exit 1
                    else
                        echo "Syntax is great, but I hope you brought sauce for the spageti"
                        exit 0
                    fi
                """,
                returnStatus: true)

                if (result != 0) {
                    currentBuild.result = 'FAILURE'
               }
            }
        }
    }


        stage('Build Makeself Installer') {
            steps {
                sh '''
                    makeself --notemp "${PROJECT_DIR}" "${INSTALLER_NAME}" "${COMMENT}" "${INSTALL_SCRIPT}"
                    echo "Installer created: ${INSTALLER_NAME}"
                '''
            }
        }
    }
}
