pipeline {
    agent {
        label 'd-workers'
    }

    environment {
        PROJECT_DIR = 'Offline_Vanilla_k8s_Installer'
        INSTALLER_NAME = 'instaler.run'
        INSTALL_SCRIPT = './automation-scripts/install.sh'
        COMMENT = 'k8s_install'
    }

    stages {
        stage('Install Required Tools') {
            steps {
                sh '''
                    apt-get update
                    apt-get install -y makeself shellcheck
                '''
            }
        }

        stage('Lint Bash Script') {
            steps {
                script {
                    def result = sh(script: "shellcheck ${INSTALL_SCRIPT}", returnStatus: true)
                    if (result != 0) {
                        echo 'syntax failed please contact dev team'
                        currentBuild.result = 'FAILURE'
                        error('Stopping build due to syntax failure.')
                    } else {
                        echo 'Syntax OK'
                    }
                }
            }
        }

        stage('Build Makeself Installer') {
            steps {
                sh '''
                    makeself --notemp "${PROJECT_DIR}" "${INSTALLER_NAME}" "${COMMENT}" "${INSTALL_SCRIPT}"
                    echo "Installer created: ${INSTALLER_NAME}"
                '''
            }
        }
    }
}
